config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :stops

  get '/destinations/:id/delete', to: "destinations#destroy", as: "delete_destination"
  get '/destinations/:id/edit', to: "destinations#edit", as: "edit_destination"
  resources :destinations, only: [:create, :new, :update, :index, :show]

  ######### Users Routes #########
  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  get "/users/:id/wishlist", to: "users#wishlist", as: "wishlist"
  post "/users/:itinerary_id/add_to_wish_list", to: "users#add_to_wish_list", as: "add_to_wish_list"
  post "/users/:itinerary_id/remove_from_wish_list", to: "users#remove_from_wish_list", as: "remove_from_wish_list"
  get "/users/feed", to: 'users#feed', as: "user_feed"
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: 'static#home', as: "root"


  ######### Sessions Routes #########
  get "/login", to: 'sessions#new', as: "login"
  post "/login", to: 'sessions#create', as: "create_session"
  get "/logout", to: 'sessions#destroy', as: "logout"

  ######### Itineraries Routes #########
  post 'itineraries/:id/like', to: "itineraries#like"
  get '/itineraries/:id/delete', to: "itineraries#destroy"
  resources :itineraries, only: [:create, :new, :show, :edit, :update, :index]do
    resources :destinations, only: [:create, :new]
    resources :stops, only: [:create, :new]
  end





end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  mount_uploader :picture_url, ItineraryPicUploader
  ##################Associations##########################
  belongs_to :user
  has_many :stops
  has_many :wishlist_itineraries
  has_many :destinations, through: :stops
  has_many :wishlist_users, through: :wishlist_itineraries, :source => 'itinerary'


  accepts_nested_attributes_for :destinations

  ##################Associations##########################
  validates :name, presence: :true
  validates :duration, presence: :true
  validates :budget_category, presence: :true



  @@budget_categories = ["< $30/Day","$30-75/Day","$75-150/Day", "> $150/Day"]

  @@regions = ["North America", "South America", "Europe", "Asia", "Africa", "Oceania"]

  def self.regions
    @@regions
  end

  def shortened_name
    if self.name.length <= 10
      self.name
    else
      "#{self.name[0..9]}..."
    end
  end

  def self.budget_categories
    @@budget_categories
  end
# Custom Setter for Budget For Sorting Purposes
  def budget
    if @budget
       @budget
     else
       if self.budget_category == "< $30/Day"
         @budget = 1
       elsif self.budget_category == "$30-75/Day"
         @budget = 2
       elsif self.budget_category == "$75-150/Day"
         @budget = 3
       elsif self.budget_category == "> $150/Day"
         @budget = 4
       end
     end
  end



  def destination_attributes=(destination_attributes)
    destination_attributes.values.each do |destination_attribute|
      destination = Destination.find_or_create_by(destination_attribute)
      self.destinations << destination
    end
  end


  def author
    self.user.user_name
  end

  def self.most_recent
    self.all.sort_by do |itinerary|
      itinerary.created_at
    end
  end

  def self.sort_by_user
    self.all.sort_by do |itinerary|
      itinerary.user.user_name
    end
  end

  def self.sort_by_budget
    self.all.sort_by do |itinerary|
      itinerary.budget
    end
  end

  def self.filter_by_destination(destination_name)

    # Captilizes first letter of each word in search query to ensure it matches DB format
    destination_name = destination_name.split.map(&:capitalize).join(' ')
    self.all.select do |itinerary|
       itinerary.destinations.any?{|destination| destination.name == destination_name}
    end
  end




end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  def index
    if  params[:search]
      @itineraries = Itinerary.filter_by_destination(params[:search])
    elsif params[:sort] == "Most Recent"
      @itineraries = Itinerary.most_recent
    elsif params[:sort] == "User"
      @itineraries = Itinerary.sort_by_user
    elsif params[:sort] == "Budget"
      @itineraries = Itinerary.sort_by_budget
    else
      @itineraries = Itinerary.all
    end
  end

  def new
    @itinerary = current_user.itineraries.build
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)
    if @itinerary.save
      redirect_to new_itinerary_destination_path(@itinerary)
    else
      render :new
    end
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    if @itinerary.update(itinerary_params)
      redirect_to(session[:return_to])
    else
      render :edit
    end

  end

  def edit
    session[:return_to] = request.referer
    @itinerary = Itinerary.find(params[:id])
  end

  def show
    @itinerary = Itinerary.find(params[:id])
  end

  def like
    session[:return_to] = request.referer
    @itinerary = Itinerary.find(params[:id])
    @itinerary.likes += 1
    @itinerary.save
    redirect_to(session[:return_to])
  end

  def destroy
    Itinerary.destroy(params[:id])
    redirect_to user_feed_path
  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:name, :duration, :budget_category,:region,:user_id, :picture_url,
      destinations_attributes: [
        :name, :duration, :description
      ]
    )
  end

end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/_destination_cards.html.erb
<%itinerary.destinations.each.with_index do |destination, index|%>
  <% if index % 3 == 0%> <div class="row"> <%end%>
    <div class="col-sm-4">
      <%= render partial: "destinations/card", locals: {destination: destination} %>
    </div>
  <%if index%3 == 2%></div> <br><br> <%end%>
<%end%>
<% if @itinerary.destinations.length % 3 != 0 %> </div> <%end%>
  <br> <br>

app/views/itineraries/_form.html.erb
<div class = "full-page-hero-image" >
  <br><br>
  <h2 class = "white-text centered">Enter Trip Details</h2>
  <div class="container-fluid transparent">
    <div class="offset-3 col-6">
      <%= render partial: "partials/form_error", locals:{object:@itinerary} %>
      <%= form_for(@itinerary) do |f|%>
        <%= f.label :picture,class: "form-text" %>
        <%= f.file_field :picture_url%>
        <%= f.label :name,class: "form-text" %>
        <%= f.text_area :name,class: "form-control" %>
        <%= f.label :region,class: "form-text" %>
        <%= f.collection_select(:region, Destination.regions, :to_s, :to_s,class: "form-control")%>
        <%= f.label :budget,class: "form-text" %>
        <%= f.collection_select(:budget_category, Itinerary.budget_categories, :to_s, :to_s, class: "form-control") %>
        <%= f.label :duration,class: "form-text" %>
        <%= f.text_area :duration, class: "form-control" %>
        <%= f.hidden_field :user_id, :value => current_user.id %> <br>
        <%= f.submit :Create,  class: "btn btn-info" %>
      <% end %>
  </div>
</div>
</div>

app/views/itineraries/_itineraries.html.erb
  <div class="col-1 offset-11 ">
    <div class="fixed social-media-bar">
      <h2><i class="fab fa-facebook-square cyan-text"></i></h2>
      <h2><i class="fab fa-instagram cyan-text"></i></h2>
      <h2><i class="fab fa-pinterest cyan-text"></i></h2>
    </div>

  </div>
  <br><br>
  <% itineraries.each do |itinerary| %>
      <div class="card col-8 offset-2" id = 'no-side-padding'>
        <div class="card-header">
          <div class="row">
            <div class="col-10">
              <img src="<%=itinerary.user.profile_pic.url%>" class = "user-feed-pic">
              <%=link_to itinerary.user.user_name, user_path(itinerary.user)%> posted
              <%=link_to itinerary.name, itinerary_path(itinerary)%>
            </div>
            <div class="col-2">
              <% if itinerary.user.id != current_user.id %>
                <!-- Follow Button -->
                  <% if !current_user.following.include?(itinerary.user)%>
                    <%= form_tag("/users/#{itinerary.user.id}/follow", method: :post) do %>
                      <%=submit_tag "Follow", class: "btn btn-info" %>
                    <%end%>
                    <!-- UnFollow Button -->
                   <%else%>
                     <%= form_tag("/users/#{itinerary.user.id}/unfollow", method: :post) do %>
                       <%=submit_tag "Unfollow",  class: "btn btn-info" %>
                     <%end%>
                  <%end%>
                <%end%>
            </div>
          </div>
        </div>
        <div class="card-body ">
          <div class="text-center">
            <% itinerary.destinations[0..4].each do |destination| %>
              <img src="<%=destination.picture_url%>" alt="" class = "destination-feed-pic">
            <%end%>
          </div>
          <br>

          <div class="row">
            <div class = 'col-6'>
              <p class="card-text no-bottom-margin">Budget: <%=itinerary.budget_category%></p>
              <p class="card-text">Region: <%=itinerary.region%></p>

            </div>
            <div class = 'col-5 offset-1 row'>
              <div class="col-6">
                <%= render partial: "partials/like_button", locals: {object:itinerary} %>
              </div>
              <div class="col-6">
                <%= render partial: "partials/wishlist_buttons", locals: {object:itinerary} %>
              </div>

            </div>
          </div>
        </div>
      </div>
      <br>

  <%end%>

app/views/itineraries/_itinerary_info.html.erb
<div class="hero-image">
  <div class="text-center centered">
    <h2 class = "white-text"><%=@itinerary.name%></h2> <br>
  </div>
  <div class = "row">
    <div class = "offset-1 col-5">
      <h4 class ="white-text">Budget Level: <%=@itinerary.budget_category%></h4>
    </div>
    <div class = "offset-2">
      <h4 class ="white-text">Duration: <%=@itinerary.duration%></h4>
    </div>
  </div>
  <div class="centered text-center">
    <h4 class ="white-text">Region: <%=@itinerary.region%></h4>
  </div>
  <img class = "profile-picture" src = '<%=@itinerary.picture_url%>'>


</div>
<br>

app/views/itineraries/_small_card.html.erb
<div class="card" style="width: 9rem;">
  <img class="card-img-top card-image-small" src="<%=itinerary.picture_url%>" alt="Card image cap">
  <div class="card-body">
    <h6 class="card-title"><%=link_to itinerary.shortened_name, itinerary_path(itinerary)%></h6>
    <%= render partial: "partials/wishlist_buttons", locals: {object: itinerary}%>
  </div>
</div>

app/views/itineraries/edit.html.erb
<%= render "form" %>

app/views/itineraries/index.html.erb
<div class="full-page-hero-image">
  <br><br><br>
  <h2 class = "white-text centered">Explore Itineraries </h2> <br><br>
  <div class="row">
    <div class="btn-toolbar mb-3 col-4" role="toolbar" aria-label="Toolbar with button groups">
       <%= link_to "Most Recent", itineraries_path(:sort => "Most Recent"), class: "btn btn-info"%>
       <%= link_to "User", itineraries_path(:sort => "User"),class: "btn btn-info" %>
       <%= link_to "Budget", itineraries_path(:sort => "Budget"),class: "btn btn-info" %>
    </div>
    <div class="input-group col-5 offset-3">
        <%=form_tag("/itineraries", method: "get", class: "form-inline") do %>
      <div class="input-group-prepend">
        <%= submit_tag "Filter By Destination", class: "input-group-text"%>
      </div>
        <%=text_field_tag :search,"" , class: "form-control"%>
      <%end%>
    </div>
  </div>

  <%= render partial: "itineraries", locals:{ itineraries: @itineraries} %>
</div>

app/views/itineraries/new.html.erb
<%= render "form" %>

app/views/itineraries/show.html.erb
<%= render "itinerary_info" %>
<div class = "container-fluid">
<!--Like Button  -->
  <div class="text-center centered">
    <%= render partial: "partials/like_button", locals: {object:@itinerary} %>
    <%= render partial: "partials/wishlist_buttons", locals: {object:@itinerary} %>

  </div>
  <!-- Displays Edit Button if Itinerary is your own -->
  <% if @itinerary.user_id == current_user.id%>
  <div class="text-center">
      <div class="btn-group">

      <%= form_tag("/itineraries/#{@itinerary.id}/edit", method: :get) do %>
        <%=submit_tag "Edit Itinerary", class: "btn btn-warning" %>
      <%end%>
      <%= form_tag("/itineraries/#{@itinerary.id}/delete", method: :get) do %>
        <%=submit_tag "Delete", class: "btn btn-danger" %>
      <%end%>
    </div>

  </div>
    <br>
  <%end%>
<br>

  <h4 class = "white-text">Stops:</h4>
  <div class="col-4 offset-4">
    <% if @itinerary.user_id == current_user.id%>
      <%= link_to "Add a Stop", new_itinerary_destination_path(@itinerary), class: "btn btn-info btn-lg btn-block"%><br><br>
    <%end%>
  </div>
  <%= render partial: "itineraries/destination_cards", locals: {itinerary: @itinerary} %>


</div>