config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :stops

  get '/destinations/:id/delete', to: "destinations#destroy", as: "delete_destination"
  get '/destinations/:id/edit', to: "destinations#edit", as: "edit_destination"
  resources :destinations, only: [:create, :new, :update, :index, :show]

  ######### Users Routes #########
  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  get "/users/:id/wishlist", to: "users#wishlist", as: "wishlist"
  post "/users/:itinerary_id/add_to_wish_list", to: "users#add_to_wish_list", as: "add_to_wish_list"
  post "/users/:itinerary_id/remove_from_wish_list", to: "users#remove_from_wish_list", as: "remove_from_wish_list"
  get "/users/feed", to: 'users#feed', as: "user_feed"
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: 'static#home', as: "root"


  ######### Sessions Routes #########
  get "/login", to: 'sessions#new', as: "login"
  post "/login", to: 'sessions#create', as: "create_session"
  get "/logout", to: 'sessions#destroy', as: "logout"

  ######### Itineraries Routes #########
  post 'itineraries/:id/like', to: "itineraries#like"
  get '/itineraries/:id/delete', to: "itineraries#destroy"
  resources :itineraries, only: [:create, :new, :show, :edit, :update, :index]do
    resources :destinations, only: [:create, :new]
    resources :stops, only: [:create, :new]
  end





end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_pic, ThumbnailUploader
  ##################Associations##########################
  has_many :itineraries
  has_many :destinations, through: :itineraries
  # Creates Wishlist
  has_many :wishlist_itineraries
  has_many :wishlist, through: :wishlist_itineraries, :source => "itinerary"

  # Creates following assocation
  has_many :active_relationships, class_name:  "Relationship",
                                 foreign_key: "follower_id",
                                 dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  ##################Validations##########################
  validates :user_name, presence: true
  validates :user_name, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_secure_password

  ##################CallBacks##########################
  before_save :capitalize_name

  ##################Methods##########################

  @@default_profile_pic

  def self.default_profile_pic
    "https://cdn.tutsplus.com/net/uploads/legacy/958_placeholders/placehold.gif"
  end
  
  def capitalize_name
    self.first_name = self.first_name.capitalize
    self.last_name = self.last_name.capitalize
  end
  #follows users
 def follow(other_user)
    self.following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    self.following.delete(other_user)
  end

  # Returns true if the current user is following the other user.

  def following?(other_user)
    self.following.include?(other_user)
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def feed
    self.following.collect do |user|
      user.itineraries.collect do |itinerary|
        itinerary
      end
    end.flatten
  end

  def feed_ordered_by_most_recent
    self.feed.sort_by do |itinerary|
      itinerary.created_at
    end
  end

  def feed_ordered_by_budget
    self.feed.sort_by do |itinerary|
      itinerary.budget
    end
  end

  def feed_ordered_by_user
    self.feed.sort_by do |itinerary|
      itinerary.user.user_name
    end
  end

  def feed_filtered_by_destination(destination_name)
    destination_name = destination_name.split.map(&:capitalize).join(' ')
    self.feed.select do |itinerary|
       itinerary.destinations.any?{|destination| destination.name == destination_name}
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
    render :layout => "no_nav"
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end



  def create

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_feed_path
    else

      render :new, :layout => "no_nav"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def feed

    @user = current_user
    if params[:search]
      @itineraries = @user.feed_filtered_by_destination(params[:search])
    elsif params[:sort] == "Most Recent"
      @itineraries = @user.feed_ordered_by_most_recent
    elsif params[:sort] == "Budget"
      @itineraries = @user.feed_ordered_by_budget
    elsif params[:sort] == "User"
      @itineraries = @user.feed_ordered_by_user
    else
      @itineraries = @user.feed
    end
  end

  def follow
    session[:return_to] = request.referer
    current_user.follow(User.find(params[:id]))
    redirect_to(session[:return_to])
  end


  def unfollow
    session[:return_to] = request.referer
    current_user.unfollow(User.find(params[:id]))
    redirect_to(session[:return_to])
  end

  def add_to_wish_list
    session[:return_to] = request.referer
    current_user.wishlist<<(Itinerary.find(params[:itinerary_id]))
    redirect_to(session[:return_to])
  end
  def remove_from_wish_list
    session[:return_to] = request.referer
    current_user.wishlist.delete(Itinerary.find(params[:itinerary_id]))
    redirect_to(session[:return_to])
  end

  def wishlist
    @itineraries = current_user.wishlist
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :first_name, :last_name,:password_confirmation,:password ,:bio, :profile_pic)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class = "full-page-hero-image">
  <br><br>
  <div class="offset-3 col-6">
  <% if @user.errors %>
    <%= render partial: "partials/form_error", locals:{object:@user} %>
  <%end%>

      <%= form_for(@user) do |f| %>
      <%= f.file_field :profile_pic %>
      <%= f.label :user_name, class: "form-text" %>
      <%= f.text_area :user_name,class: "form-control"%>
      <%= f.label :first_name, class: "form-text" %>
      <%= f.text_area :first_name, class: "form-control"%>
      <%= f.label :last_name, class: "form-text"%>
      <%= f.text_area :last_name, class: "form-control"%> <br>
      <%= f.submit :Submit,  class: "btn btn-info" %>
      <%end%>

  </div>

</div>

app/views/users/feed.html.erb
<div class="full-page-hero-image">
  <br>

    <h2 class= "white-text centered">Explore Your Feed </h2> <br><br>
    <div class="row">
    <div class="btn-toolbar mb-3 col-4" role="toolbar" aria-label="Toolbar with button groups">
       <%= link_to "Most Recent", user_feed_path(:sort => "Most Recent"), class: "btn btn-info"%>
       <%= link_to "User", user_feed_path(:sort => "User"),class: "btn btn-info" %>
       <%= link_to "Budget", user_feed_path(:sort => "Budget"),class: "btn btn-info" %>
    </div>
    <div class="input-group col-5 offset-3">
      <%=form_tag("/users/feed", method: "get", class: "form-inline") do %>
        <div class="input-group-prepend">
          <%= submit_tag "Filter By Destination", class: "input-group-text"%>
        </div>
        <%=text_field_tag :search,"" , class: "form-control"%>
        <%end%>
    </div>
  </div>



  <% if @itineraries.empty? %>
  <br><br>
    <div class="centered">
      <p class = "white-text">You Don't Currently Follow Anyone</p>
      <p><%= link_to "Browse Itineraries", itineraries_path, class: "btn btn-info"%> </p>
    </div>
  <%else %>
    <%= render partial: 'itineraries/itineraries', locals: {itineraries: @itineraries} %>
  <%end%>
</div>

app/views/users/new.html.erb
<div class = "full-page-hero-image">
  <br><br>
  <div class="offset-3 col-6">
  <% if @user.errors %>
    <%= render partial: "partials/form_error", locals:{object:@user} %>
  <%end%>

      <%= form_for(@user) do |f| %>
      <%= f.file_field :profile_pic %>
      <%= f.label :user_name, class: "form-text" %>
      <%= f.text_area :user_name,class: "form-control"%>
      <%= f.label :password, class: "form-text" %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :first_name, class: "form-text" %>
      <%= f.text_area :first_name, class: "form-control"%>
      <%= f.label :last_name, class: "form-text"%>
      <%= f.text_area :last_name, class: "form-control"%> <br>
      <%= f.submit :Create,  class: "btn btn-info" %>
      <%end%>

  </div>

</div>

app/views/users/show.html.erb
<div class ='hero-image'>
    <br>
    <h4 class= "profile-name text-center"><%=@user.full_name%></h4> <br>
    <img class = "profile-picture" src = '<%=@user.profile_pic.url%>'>

  </div>

</div>

<div class ="container-fluid">
  <% if @user.id == current_user.id %>

    <div class="centered">
      <%=link_to "Edit Profile", edit_user_path(@user), class: "btn btn-warning"%>

    </div>
  <%else%>
  <div class="centered">
      <!-- Follow Button -->
      <% if !current_user.following.include?(@user)%>
        <%= form_tag("/users/#{@user.id}/follow", method: :post) do %>
          <%=submit_tag "Follow", class: "btn btn-info" %>
        <%end%>
        <!-- UnFollow Button -->
       <%else%>
       <%= form_tag("/users/#{@user.id}/unfollow", method: :post) do %>
         <%=submit_tag "Unfollow",  class: "btn btn-info" %>
       <%end%>
      <%end%>
  </div>
  <%end%>
  <!-- Displays option to add itinerary if you are looking at your own profile -->
  <% if @user.id == current_user.id%>
    <div class="centered">
      <%= form_tag("/itineraries/new", method: :get) do %>
        <%=submit_tag "Create New Itinerary", class: "btn btn-info" %>
      <%end%>
    </div>
  <%end%>

  <!-- User's Itineraries -->
<br>
<div class="offset-1">
  <h5 class="white-text"><%="#{@user.first_name}'s Itineraries"%></h5> <br>
    <%@user.itineraries.each.with_index do |itinerary, index|%>
      <% if index % 5 == 0%> <div class="row"> <%end%>
        <div class="col-sm-2">
          <%= render partial: "itineraries/small_card", locals: {itinerary: itinerary} %>
        </div>
      <%if index%5 == 4%></div> <br> <%end%>
    <%end%>
    <% if @user.itineraries.length % 5 != 0 %> </div> <%end%> <br>



  <!-- Users Destinations -->
  <h5 class="white-text"><%="#{@user.first_name}'s Destinations"%></h5> <br>
      <%@user.destinations.each.with_index do |destination, index|%>
        <% if index % 5 == 0%> <div class="row"> <%end%>
          <div class="col-sm-2">
            <%= render partial: "destinations/card_small", locals: {destination: destination} %>
          </div>
        <%if index%5 == 4%></div> <br> <%end%>
    <%end%>
      <% if @user.destinations.length % 5 != 0 %> </div> <%end%>

      <h5 class="white-text"><%="#{@user.first_name}'s Wishlist"%></h5> <br>
        <%@user.wishlist.each.with_index do |itinerary, index|%>
          <% if index % 5 == 0%> <div class="row"> <%end%>
            <div class="col-sm-2">
              <%= render partial: "itineraries/small_card", locals: {itinerary: itinerary} %>
            </div>
          <%if index%5 == 4%></div> <br> <%end%>
        <%end%>
        <% if @user.itineraries.length % 5 != 0 %> </div> <%end%> <br>

  </div>


</div>

app/views/users/wishlist.html.erb
<div class = "full-page-hero-image" >
  <br><br>
  <h2 class = "white-text centered">Your Wishlist</h2>
  <br><br>
  <div class="container-fluid transparent">
    <% if @itineraries.empty? %>
    <br><br>
      <div class="centered">
        <p class = "white-text">You Don't Currently have any items in your wishlist</p>
        <p><%= link_to "Browse Itineraries", itineraries_path, class: "btn btn-info"%> </p>
      </div>
    <%else %>
    <%@itineraries.each.with_index do |itinerary, index|%>
      <% if index % 3 == 0%> <div class="row"> <%end%>
        <div class="col-sm-4">
          <div class="card" style="width: 18rem;">
            <img class="card-img-top card-image" src="<%=itinerary.picture_url%>" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><%=link_to itinerary.name, itineraries_path(itinerary)%></h5>
              <p class="card-text">Author: <%=link_to itinerary.user.user_name, user_path(itinerary.user)%></p>
              <p class="card-text">Budget: <%=itinerary.budget_category%></p>
              <p class="card-text">Length: <%=itinerary.duration%></p>
            <div class="card-body centered">
              <%= render partial: "partials/wishlist_buttons", locals: {object:itinerary} %>
            </div>
          </div>
        </div>
      </div>
        <%if index%3 == 2%></div> <br><br> <%end%>
      <%end%>
    <% if @itineraries.length % 3 != 0 %> </div> <%end%>
    <br> <br>
  </div>
  <%end%>

</div>