config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :stops

  get '/destinations/:id/delete', to: "destinations#destroy", as: "delete_destination"
  get '/destinations/:id/edit', to: "destinations#edit", as: "edit_destination"
  resources :destinations, only: [:create, :new, :update, :index, :show]

  ######### Users Routes #########
  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  get "/users/:id/wishlist", to: "users#wishlist", as: "wishlist"
  post "/users/:itinerary_id/add_to_wish_list", to: "users#add_to_wish_list", as: "add_to_wish_list"
  post "/users/:itinerary_id/remove_from_wish_list", to: "users#remove_from_wish_list", as: "remove_from_wish_list"
  get "/users/feed", to: 'users#feed', as: "user_feed"
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: 'static#home', as: "root"


  ######### Sessions Routes #########
  get "/login", to: 'sessions#new', as: "login"
  post "/login", to: 'sessions#create', as: "create_session"
  get "/logout", to: 'sessions#destroy', as: "logout"

  ######### Itineraries Routes #########
  post 'itineraries/:id/like', to: "itineraries#like"
  get '/itineraries/:id/delete', to: "itineraries#destroy"
  resources :itineraries, only: [:create, :new, :show, :edit, :update, :index]do
    resources :destinations, only: [:create, :new]
    resources :stops, only: [:create, :new]
  end





end

app/models/destination.rb
class Destination < ApplicationRecord
  ##################Mounting Uploader##########################
  # mount_uploader :picture_url, DestinationPicUploader

  ##################Associations##########################
  has_many :stops
  has_many :itineraries, through: :stops
  has_many :users, through: :itineraries

  ##################CallBacks##########################
  before_save :capitalize_name

  ##################Validation##########################
  validates :name, presence: true
  validates :region, presence: true
  validates :description, presence: true

  @@regions = ["North America", "South America", "Europe", "Asia", "Africa", "Oceania"]

  def self.regions
    @@regions
  end

  def self.destinations_which_match_itinerary_region(itinerary)
    self.all.select do |destination|
      byebug
      destination.region == itinerary.region
    end
  end

  private
  #ensures uniform format for destination names to aid search queries
  def capitalize_name
    self.name = self.name.split.map(&:capitalize).join(' ')
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  def new
    @itinerary = Itinerary.find(params[:itinerary_id])
    @destination = Destination.new
  end

  def create
    @itinerary =  Itinerary.find(params[:destination][:itinerary_id])
    @destination = Destination.new(destination_params)
    if @destination.save
      @itinerary.destinations << @destination
      redirect_to new_itinerary_destination_path(@itinerary)
    else
      render :new
    end
  end

  def edit
    session[:return_to] = request.referer
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update(destination_params)
      redirect_to(session[:return_to])
    else
      render :edit
    end

  end

  def destroy
    session[:return_to] = request.referer
    Destination.destroy(params[:id])
    Stop.find_by(destination_id: params[:id]).destroy
    redirect_to(session[:return_to])
  end


  private

  def destination_params
    params.require(:destination).permit(:name, :description, :region, :picture_url)
  end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_card.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top card-image" src="<%=destination.picture_url%>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%=destination.name%></h5>
    <p class="card-text"><%=destination.description%></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Continent: <%=destination.region%></li>

  </ul>
  <div class="card-body">
    <!-- Display Stop Edit and Delete Buttons For Your Own Itineraries -->
    <% if @itinerary.user_id == current_user.id%>
      <%= link_to "Edit Stop", edit_destination_path(destination), class: "btn btn-warning"%>
      <%= link_to "Delete Stop", delete_destination_path(destination), class:"btn btn-danger"%>
    <%end%>
  </div>
</div>

app/views/destinations/_card_small.html.erb
<div class="card" style="width: 9rem;">
  <img class="card-img-top card-image-small" src="<%=destination.picture_url%>" alt="Card image cap">
  <div class="card-body">
    <h6 class="card-title"><%=destination.name[0..10]%></h6>
  </div>
</div>

app/views/destinations/edit.html.erb
<div class = "hero-image-small" >
  <h5 class = "hero-text">Edit <%=@destination.name%></h5>
</div>
<div class="container-fluid">
  <div class="offset-3 col-6">
      <% if @destination.errors %>
        <%= render partial: "partials/form_error", locals:{object:@destination} %>
      <%end%><br>
      <%= render "partials/destinations/form" %>
  </div>
</div>

app/views/destinations/new.html.erb
<%= render "itineraries/itinerary_info"%>
<div class="container-fluid">
  <div class="text-center">
    <%= form_tag("/itineraries/#{@itinerary.id}/edit", method: :get) do %>
      <%=submit_tag "Edit Itinerary Details", class: "btn btn-info" %>
    <%end%>
  </div>
  <br>
  <h4 class = "text-center white-text">Add a Stop</h4>
  <% if @destination.errors %>
    <% @destination.errors.full_messages.each do |message| %>
      <p class = "error"><%=message%></p>
    <%end%>
  <%end%>
  <div class="offset-3 col-6">
    <%= form_for(@destination) do |f|%>
      <%= f.label :Stop_Location, class: "form-text" %>
      <%= f.text_area :name, class: "form-control" %>
      <%= f.label :Region, class: "form-text" %>
      <%= f.collection_select(:region, Destination.regions, :to_s, :to_s,class: "form-control")%>
      <%= f.label :description, class: "form-text" %>
      <%= f.text_area :description, class: "form-control" %>
      <%= f.hidden_field :itinerary_id, :value => @itinerary.id %> <br>
      <%= f.submit :Create, class: "btn btn-info" %>
    <%end%>
  </div>
    <h4 class = "text-center white-text">Current Stops</h4>
    <% if !@itinerary.destinations.empty?%>
      <%= render partial: "itineraries/destination_cards", locals: {itinerary: @itinerary} %>
    <% else %>
      <p class = "white-text">Currently Have No stops</p>
    <%end%>

</div>