config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :stops

  get '/destinations/:id/delete', to: "destinations#destroy", as: "delete_destination"
  get '/destinations/:id/edit', to: "destinations#edit", as: "edit_destination"
  resources :destinations, only: [:create, :new, :update, :index, :show]

  ######### Users Routes #########
  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  get "/users/:id/wishlist", to: "users#wishlist", as: "wishlist"
  post "/users/:itinerary_id/add_to_wish_list", to: "users#add_to_wish_list", as: "add_to_wish_list"
  post "/users/:itinerary_id/remove_from_wish_list", to: "users#remove_from_wish_list", as: "remove_from_wish_list"
  get "/users/feed", to: 'users#feed', as: "user_feed"
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: 'static#home', as: "root"


  ######### Sessions Routes #########
  get "/login", to: 'sessions#new', as: "login"
  post "/login", to: 'sessions#create', as: "create_session"
  get "/logout", to: 'sessions#destroy', as: "logout"

  ######### Itineraries Routes #########
  post 'itineraries/:id/like', to: "itineraries#like"
  get '/itineraries/:id/delete', to: "itineraries#destroy"
  resources :itineraries, only: [:create, :new, :show, :edit, :update, :index]do
    resources :destinations, only: [:create, :new]
    resources :stops, only: [:create, :new]
  end





end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travellr</title>
    <!-- Jquery Script -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.js Script -->
    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- Bootstrap Complete JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Complete CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-dark fixed-top  ">
    <a class="navbar-brand white-text" href="/users/feed"><i class="far fa-compass"></i>Travellr</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Profile", user_path(current_user), class: "nav-link white-text"%>
      </li>
      <li class="nav-item active">
        <%= link_to "Feed", user_feed_path, class: "nav-link white-text" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Browse", itineraries_path, class: "nav-link white-text" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Wishlist", wishlist_path(current_user), class: "nav-link white-text" %>
      </li>
    </ul>
    <%= link_to "Create Itinerary", new_itinerary_path, class: "btn btn-light my-2 my-sm-0" %>
    <%= link_to "Log Out", logout_path, class:"btn btn-info my-2 my-sm-0" %>
  </div>
</nav>
<br><br>
  <%= yield %>
</body>
</html>

app/views/layouts/no_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travellr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Jquery Script -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.js Script -->
    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- Bootstrap Complete JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Complete CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>